version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: currency-app
    container_name: currency-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - .:/app
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - currency-network
    links:
      - redis

  redis:
    image: redis:latest
    container_name: currency-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - currency-network 

networks:
  currency-network:
    driver: bridge

volumes:
  redis:
    driver: local
